config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: 'admin/sessions',
  }
  namespace :admin do
    get 'top' => 'homes#top', as: 'top'
    get 'search' => 'homes#search', as: 'search'
    get 'customers/:customer_id/orders' => 'orders#index', as: 'customer_orders'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items, except: [:destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :orders, only: [:index, :show, :update] do
      resources :order_details, only: [:update]
    end
  end

  devise_for :customers, skip: [:passwords,] ,controllers: {
    sessions: 'public/sessions',
    registrations: 'public/registrations',
  }

  scope module: :public do
    root 'items#top'
    get 'homes/about' => 'homes#about'
    get 'customers/mypage' => 'customers#show', as: 'mypage'
    get 'customers/information/edit' => 'customers#edit', as: 'edit_information'
    patch 'customers/information' => 'customers#update', as: 'update_information'
    put 'customers/information' => 'customers#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'confirm_unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw_customer'
    put 'customers/withdraw' => 'customers#withdraw'
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all_cart_items'
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/confirm' => 'orders#error'
    get 'orders/thanks' => 'orders#thanks', as: 'thanks'

    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    resources :items, only: [:index, :show] do
    resources :cart_items, only: [:create, :update, :destroy]
    end
    resources :cart_items, only: [:index]
    resources :orders, only: [:new, :index, :create, :show]
  end
end

app/views/layouts/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>エラーが発生しました。以下ご確認お願いいたします。</h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="<%= (admin_signed_in? ? "admin_header" : "" ) %>">
          <nav class="navbar navbar-expand-sm navbar-light text-dark bg-dark" id="home">
            <%= link_to 'NaganoCake', (admin_signed_in? ? admin_posts_path : root_path ), class: "nav-link text-white" %>
            <ul class="navbar-nav flex">
              <% if admin_signed_in? %>
                <li><%= link_to '所品一覧', admin_items_path, class: "nav-link text-white" %></li>
                <li><%= link_to 'ユーザー一覧', admin_customers_path, class: "nav-link text-white" %></li>
                <li><%= link_to '注文履歴一覧', admin_customer_orders_path, class: "nav-link text-white" %></li>
                <li><%= link_to 'ジャンル一覧', admin_genres_path, class: "nav-link text-white" %></li>
                <li><%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: "nav-link text-white" %></li>
              <% elsif customer_signed_in? %>
                <li><%= link_to 'マイページ', mypage_path, class: "nav-link text-white" %></li>
                <li><%= link_to '商品一覧', items_path, class: "nav-link text-white" %></li>
                <li><%= link_to 'カート', cart_items_path, class: "nav-link text-white" %></li>
                <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "nav-link text-white" %></li>
              <% else %>
                <li><%= link_to 'About', homes_about_path, class: "nav-link text-white" %></li>
                <li><%= link_to '商品一覧', items_path, class: "nav-link text-white" %></li>
                <li><%= link_to '新規登録', new_customer_registration_path, class: "nav-link text-white" %></li>
                <li><%= link_to 'ログイン', new_customer_session_path, class: "nav-link text-white" %></li>
              <% end %>
             </ul>
          </nav>
    </header>
    <%= yield %>
  </body>
</html>